### ISSUE TITLE
Remove redundant path references all over the place

### ISSUE THREAD

**Issue by marsmith** [marsmith/ADONNIS#10]

**Comment by ianscilipoti-usgs** [comment]
This is pretty much done. The testing suite and throughout gdalcode.py the references to paths are replaced by passing around a gdalData object. The only exception is in Namer.py. Eventually this should be changed too but right now it is only being called from php so getting the gdal data object to it cannot be done the same way. Namer.py can possibly just construct its on data object on the fly but there might be a better way..
